# fusion des bases AGB - CARTOSUD

alter table agb_exploitation add "ORA_GEOMETRY" "MDSYS"."SDO_GEOMETRY";
update agb_exploitation agb set ORA_GEOMETRY = ( select ORA_GEOMETRY from CS_CONTOUR_EXPLOITATION  cs where  agb.numex = cs.numex and cs.numex <> 'YE 00010');

alter table agb_abreuvoir add "ORA_GEOMETRY" "MDSYS"."SDO_GEOMETRY";
update agb_abreuvoir agb set ORA_GEOMETRY = ( select ORA_GEOMETRY from cs_abreuvoirs  cs where  agb.num = cs.num);

alter table agb_barriere add "ORA_GEOMETRY" "MDSYS"."SDO_GEOMETRY";
update agb_barriere set ORA_GEOMETRY = ( select ORA_GEOMETRY from cs_barrieres cs where  agb.num = cs.num and agb.num <> null and agb.num <> 'Barriere_11350');

alter table agb_batiment add "ORA_GEOMETRY" "MDSYS"."SDO_GEOMETRY";
update agb_batiment set ORA_GEOMETRY = ( select ORA_GEOMETRY from cs_batiments  cs where  agb.num = cs.num);

alter table agb_conduite add "ORA_GEOMETRY" "MDSYS"."SDO_GEOMETRY";
update agb_conduite set ORA_GEOMETRY = ( select ORA_GEOMETRY from cs_conduites  cs where  agb.num = cs.num);

alter table agb_cuve add "ORA_GEOMETRY" "MDSYS"."SDO_GEOMETRY";
update agb_cuve set ORA_GEOMETRY = ( select ORA_GEOMETRY from cs_cuves  cs where  agb.num = cs.num);

alter table agb_parcelle add "ORA_GEOMETRY" "MDSYS"."SDO_GEOMETRY";
update agb_parcelle set ORA_GEOMETRY = ( select ORA_GEOMETRY from cs_parcelles  cs where  agb.num = cs.num);

alter table agb_prise_eau add "ORA_GEOMETRY" "MDSYS"."SDO_GEOMETRY";
update agb_prise_eau set ORA_GEOMETRY = ( select ORA_GEOMETRY from cs_prise_d_eau  cs where  agb.num = cs.num);

alter table agb_retenue add "ORA_GEOMETRY" "MDSYS"."SDO_GEOMETRY";
update agb_retenue set ORA_GEOMETRY = ( select ORA_GEOMETRY from cs_retenues  cs where  agb.num = cs.num);




CREATE INDEX "AGB_ABERUVOIR_SPX" ON "AGB_ABREUVOIR"
  (
    "GEOMETRY"
  )
INDEXTYPE IS "MDSYS"."SPATIAL_INDEX" PARAMETERS ('sdo_indx_dims=2 , layer_gtype=MULTIPOINT, tablespace=AGB_IDX');

INSERT INTO "USER_SDO_GEOM_METADATA" (TABLE_NAME,COLUMN_NAME,DIMINFO,SRID) VALUES ('AGB_ABREUVOIR','ORA_GEOMETRY',MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X',300000,600000,0.005),MDSYS.SDO_DIM_ELEMENT('Y',100000,400000,0.005),MDSYS.SDO_DIM_ELEMENT('Z',100000,400000,0.002)),null);


CREATE INDEX "AGB_EXPLOITATION_SPX" ON "AGB_EXPLOITATION"
  (
    "ORA_GEOMETRY"
  )
INDEXTYPE IS "MDSYS"."SPATIAL_INDEX" PARAMETERS ('sdo_indx_dims=2 , layer_gtype=MULTIPOLYGON, tablespace=AGB_IDX');

INSERT INTO "USER_SDO_GEOM_METADATA" (TABLE_NAME,COLUMN_NAME,DIMINFO,SRID) VALUES ('AGB_EXPLOITATION','ORA_GEOMETRY',MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X',300000,600000,0.005),MDSYS.SDO_DIM_ELEMENT('Y',100000,400000,0.005),MDSYS.SDO_DIM_ELEMENT('Z',100000,400000,0.002)),null);

CREATE INDEX "agb_barriere_SPX" ON "agb_barriere"
  (
    "ORA_GEOMETRY"
  )
INDEXTYPE IS "MDSYS"."SPATIAL_INDEX" PARAMETERS ('sdo_indx_dims=2 , layer_gtype=MULTILINE, tablespace=AGB_IDX');

INSERT INTO "USER_SDO_GEOM_METADATA" (TABLE_NAME,COLUMN_NAME,DIMINFO,SRID) VALUES ('agb_barriere','ORA_GEOMETRY',MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X',300000,600000,0.005),MDSYS.SDO_DIM_ELEMENT('Y',100000,400000,0.005),MDSYS.SDO_DIM_ELEMENT('Z',100000,400000,0.002)),null);

CREATE INDEX "agb_batiment_SPX" ON "agb_batiment"
  (
    "ORA_GEOMETRY"
  )
INDEXTYPE IS "MDSYS"."SPATIAL_INDEX" PARAMETERS ('sdo_indx_dims=2 , layer_gtype=MULTIPOLYGON, tablespace=AGB_IDX');

INSERT INTO "USER_SDO_GEOM_METADATA" (TABLE_NAME,COLUMN_NAME,DIMINFO,SRID) VALUES ('agb_batiment','ORA_GEOMETRY',MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X',300000,600000,0.005),MDSYS.SDO_DIM_ELEMENT('Y',100000,400000,0.005),MDSYS.SDO_DIM_ELEMENT('Z',100000,400000,0.002)),null);

CREATE INDEX "agb_conduite_SPX" ON "agb_conduite"
  (
    "ORA_GEOMETRY"
  )
INDEXTYPE IS "MDSYS"."SPATIAL_INDEX" PARAMETERS ('sdo_indx_dims=2 , layer_gtype=MULTILINE, tablespace=AGB_IDX');

INSERT INTO "USER_SDO_GEOM_METADATA" (TABLE_NAME,COLUMN_NAME,DIMINFO,SRID) VALUES ('agb_conduite','ORA_GEOMETRY',MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X',300000,600000,0.005),MDSYS.SDO_DIM_ELEMENT('Y',100000,400000,0.005),MDSYS.SDO_DIM_ELEMENT('Z',100000,400000,0.002)),null);

CREATE INDEX "AGB_CUVE_SPX" ON "AGB_CUVE"
  (
    "GEOMETRY"
  )
INDEXTYPE IS "MDSYS"."SPATIAL_INDEX" PARAMETERS ('sdo_indx_dims=2 , layer_gtype=MULTIPOINT, tablespace=AGB_IDX');

INSERT INTO "USER_SDO_GEOM_METADATA" (TABLE_NAME,COLUMN_NAME,DIMINFO,SRID) VALUES ('AGB_CUVE','ORA_GEOMETRY',MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X',300000,600000,0.005),MDSYS.SDO_DIM_ELEMENT('Y',100000,400000,0.005),MDSYS.SDO_DIM_ELEMENT('Z',100000,400000,0.002)),null);

CREATE INDEX "agb_parcelle_SPX" ON "agb_parcelle"
  (
    "ORA_GEOMETRY"
  )
INDEXTYPE IS "MDSYS"."SPATIAL_INDEX" PARAMETERS ('sdo_indx_dims=2 , layer_gtype=MULTIPOLYGON, tablespace=AGB_IDX');

INSERT INTO "USER_SDO_GEOM_METADATA" (TABLE_NAME,COLUMN_NAME,DIMINFO,SRID) VALUES ('agb_parcelle','ORA_GEOMETRY',MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X',300000,600000,0.005),MDSYS.SDO_DIM_ELEMENT('Y',100000,400000,0.005),MDSYS.SDO_DIM_ELEMENT('Z',100000,400000,0.002)),null);

CREATE INDEX "AGB_PRISE_EAU_SPX" ON "AGB_PRISE_EAU"
  (
    "GEOMETRY"
  )
INDEXTYPE IS "MDSYS"."SPATIAL_INDEX" PARAMETERS ('sdo_indx_dims=2 , layer_gtype=MULTIPOINT, tablespace=AGB_IDX');

INSERT INTO "USER_SDO_GEOM_METADATA" (TABLE_NAME,COLUMN_NAME,DIMINFO,SRID) VALUES ('AGB_PRISE_EAU','ORA_GEOMETRY',MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X',300000,600000,0.005),MDSYS.SDO_DIM_ELEMENT('Y',100000,400000,0.005),MDSYS.SDO_DIM_ELEMENT('Z',100000,400000,0.002)),null);

CREATE INDEX "agb_retenue_SPX" ON "agb_retenue"
  (
    "ORA_GEOMETRY"
  )
INDEXTYPE IS "MDSYS"."SPATIAL_INDEX" PARAMETERS ('sdo_indx_dims=2 , layer_gtype=MULTILINE, tablespace=AGB_IDX');

INSERT INTO "USER_SDO_GEOM_METADATA" (TABLE_NAME,COLUMN_NAME,DIMINFO,SRID) VALUES ('agb_retenue','ORA_GEOMETRY',MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X',300000,600000,0.005),MDSYS.SDO_DIM_ELEMENT('Y',100000,400000,0.005),MDSYS.SDO_DIM_ELEMENT('Z',100000,400000,0.002)),null);


