#supprimer les données 

DELETE FROM "MDSYS"."USER_SDO_GEOM_METADATA" WHERE TABLE_NAME = 'AGB_EXPLOITATION';

DELETE FROM "SDE"."LAYERS" WHERE TABLE_NAME = 'AGB_EXPLOITATION';

DELETE FROM "SDE"."COLUMN_REGISTRY" WHERE TABLE_NAME = 'AGB_EXPLOITATION';

DELETE FROM "SDE"."GEOMETRY_COLUMNS" WHERE F_TABLE_NAME = 'AGB_EXPLOITATION';